%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/mauro/Downloads/defbuffer1.csv
%
% Auto-generated by MATLAB on 20-Apr-2023 10:26:19

%% Define the file name
filename = "/home/mauro/Downloads/defbuffer1.csv";

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = [10, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Index", "Reading", "Unit", "RangeDigits", "DispDigits", "Math", "StartGroup", "Limit1High", "Limit1Low", "Limit2High", "Limit2Low", "Terminal", "Questionable", "Origin", "Date", "Time", "FractionalSeconds", "Channel", "CHLabel"];
opts.VariableTypes = ["double", "double", "categorical", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "datetime", "datetime", "double", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "CHLabel", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Unit", "Math", "StartGroup", "Limit1High", "Limit1Low", "Limit2High", "Limit2Low", "Terminal", "Questionable", "Origin", "Channel", "CHLabel"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "MM/dd/yyyy");
opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Index = tbl.Index;
V = tbl.Reading;
Unit = tbl.Unit;
Date = tbl.Date;
Time = tbl.Time;
FractionalSeconds = tbl.FractionalSeconds;

%% Clear temporary variables
clear opts tbl

%% Convert into seconds
utc = convertTo(Time, 'posixtime');
t = utc - utc(1) + FractionalSeconds;

%% Prepare a plot
figure
plot(t, V)
hold on
grid on
xlabel("Time (s)")
ylabel(sprintf("V (%s)", Unit(1)))
